### ISSUE TITLE
Missing script and utils folders

### ISSUE THREAD

**Issue by XiongSongge** [yanzhh/HGERE#1]
run_hgnn.py uses files in the script and utils folders, but these two folders are not included in the uploaded code. Have these two folders been missed?Or do I need to download them from elsewhere?

run_hgnn.py
-------------------------------
from utils.data import Dataset
from utils.metric import *
from scripts.analysis.evalfile import *

**Comment by yanzhh** [comment]
Thanks for your interest in our research. The missing folder "utils" has now been added and the code has been updated to address the issue.

**Comment by XiongSongge** [comment]
I have received it.Thanks you for your wonderful job.



---- Replied Message ----
| From | ***@***.***> |
| Date | 01/03/2024 20:15 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [yanzhh/HGERE] Missing script and utils folders (Issue #1) |

Thanks for your interest in our research. The missing folder "utils" has now been added and the code has been updated to address the issue.
